### ISSUE TITLE
Consider using symbols as variable names instead of words

### ISSUE THREAD

**Issue by tdmorello** [peng-lab/PyBaSiC#3]
Variable names could be symbols instead of words.

e.g.:

eplson = ε
mu = µ
mu_bar = µ_bar (can't find unicode for this)
rho = ρ
A1_hat = Â1
E1_hat = Ê1

**Comment by yfukai** [comment]
Hi, thanks @tdmorello for opening this issue! As @Nicholas-Schaub mentioned, I understand this as to increase readability with scarification of "input-ability" (and potential problems with editors). As we always need to make some conversion b/w equations and codes, I think my balance tilts towards the input-ability (Latin notations).

**Comment by tdmorello** [comment]
Good points!
